### ISSUE TITLE
Invastigate bridge issue right after fully synced node

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/blockchain#452]
After start via the quickstart, the bridge waits for the node to be synced. After is has synced the following error occurs. 
This happens several times, but after a while it seems to be fine. 
```
2019-10-08 14:15:40,949 INFO     [wait_for_start_block] bridge.main: foreign node is synced until block number 1280559 of 1435033, but hasn't reached event fetch start block number 1321331 yet. Waiting...
2019-10-08 14:15:45,958 INFO     [wait_for_start_block] bridge.main: foreign node is synced until block number 1293564 of 1435034, but hasn't reached event fetch start block number 1321331 yet. Waiting...
2019-10-08 14:15:50,965 INFO     [wait_for_start_block] bridge.main: foreign node is synced until block number 1303885 of 1435034, but hasn't reached event fetch start block number 1321331 yet. Waiting...
2019-10-08 14:15:55,973 INFO     [wait_for_start_block] bridge.main: foreign node is synced until block number 1318703 of 1435034, but hasn't reached event fetch start block number 1321331 yet. Waiting...
2019-10-08 14:16:00,982 INFO     [wait_for_start_block] bridge.main: foreign node is synced until block number 1332136 of 1435035 and has passed the event fetch start block number 1321331
2019-10-08 14:16:11,044 ERROR    [main] bridge.main: Application error
Traceback (most recent call last):
  File "/opt/bridge/lib/python3.6/site-packages/bridge/main.py", line 560, in main
    main_services = make_main_services(config, recorder, stop_pool)
  File "/opt/bridge/lib/python3.6/site-packages/bridge/main.py", line 374, in make_main_services
    transfer_event_fetcher = make_transfer_event_fetcher(config, transfer_event_queue)
  File "/opt/bridge/lib/python3.6/site-packages/bridge/main.py", line 215, in make_transfer_event_fetcher
    validate_contract_existence(token_contract)
  File "/opt/bridge/lib/python3.6/site-packages/bridge/contract_validation.py", line 18, in validate_contract_existence
    contract_code = contract.web3.eth.getCode(contract.address)
  File "/opt/bridge/lib/python3.6/site-packages/web3/eth.py", line 137, in getCode
    [account, block_identifier],
  File "/opt/bridge/lib/python3.6/site-packages/web3/manager.py", line 97, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32042, 'message': 'Bad response on requests: [ Account, Code ]. Error cause was EmptyResponse, (majority count: 773 / total: 773)'}
2019-10-08 14:16:11,045 INFO     [main] bridge.main: Stopping...
2019-10-08 14:16:14,478 INFO     [main] bridge.main: Loading configuration file from /config/config.toml
2019-10-08 14:16:15,494 INFO     [main] bridge.main: Starting Trustlines Bridge Validation Server for address 0x60F7cd22475426E158FeB0541e666812E5cedC74
2019-10-08 14:16:15,494 INFO     [main] bridge.service: Starting wait_for_start_block service
2019-10-08 14:16:15,526 INFO     [wait_for_start_block] bridge.main: home node is fully synced to head number 4406115 and has passed the event fetch start block number 4153205
2019-10-08 14:16:15,545 INFO     [wait_for_start_block] bridge.main: foreign node is synced until block number 1359767 of 1435036 and has passed the event fetch start block number 1321331
2019-10-08 14:16:25,585 ERROR    [main] bridge.main: Application error
Traceback (most recent call last):
  File "/opt/bridge/lib/python3.6/site-packages/bridge/main.py", line 560, in main
    main_services = make_main_services(config, recorder, stop_pool)
  File "/opt/bridge/lib/python3.6/site-packages/bridge/main.py", line 374, in make_main_services
    transfer_event_fetcher = make_transfer_event_fetcher(config, transfer_event_queue)
  File "/opt/bridge/lib/python3.6/site-packages/bridge/main.py", line 215, in make_transfer_event_fetcher
    validate_contract_existence(token_contract)
  File "/opt/bridge/lib/python3.6/site-packages/bridge/contract_validation.py", line 18, in validate_contract_existence
    contract_code = contract.web3.eth.getCode(contract.address)
  File "/opt/bridge/lib/python3.6/site-packages/web3/eth.py", line 137, in getCode
    [account, block_identifier],
  File "/opt/bridge/lib/python3.6/site-packages/web3/manager.py", line 97, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32042, 'message': 'Bad response on requests: [ Account, Code ]. Error cause was EmptyResponse, (majority count: 941 / total: 941)'}
2019-10-08 14:16:25,586 INFO     [main] bridge.main: Stopping...
```

**Comment by cducrest** [comment]
For info the bridged token was deployed at block 1_321_315 so before the event fetch start block and the complaint that the contract has no code is unjustified.
